// @ts-nocheck
export const ADDITIONAL_TRAVEL_CITIES = [
  {
    rank: 101,
    name: "Austin",
    slug: "austin",
    country: "United States",
    region: "TX",
    lat: 30.2672,
    lng: -97.7431,
    airportCodes: ["AUS"],
  },
  {
    rank: 102,
    name: "Atlanta",
    slug: "atlanta",
    country: "United States",
    region: "GA",
    lat: 33.749,
    lng: -84.388,
    airportCodes: ["ATL"],
  },
  {
    rank: 103,
    name: "Dallas",
    slug: "dallas",
    country: "United States",
    region: "TX",
    lat: 32.7767,
    lng: -96.797,
    airportCodes: ["DFW", "DAL"],
  },
  {
    rank: 104,
    name: "Houston",
    slug: "houston",
    country: "United States",
    region: "TX",
    lat: 29.7604,
    lng: -95.3698,
    airportCodes: ["IAH", "HOU"],
  },
  {
    rank: 105,
    name: "Philadelphia",
    slug: "philadelphia",
    country: "United States",
    region: "PA",
    lat: 39.9526,
    lng: -75.1652,
    airportCodes: ["PHL"],
  },
  {
    rank: 106,
    name: "Phoenix",
    slug: "phoenix",
    country: "United States",
    region: "AZ",
    lat: 33.4484,
    lng: -112.074,
    airportCodes: ["PHX"],
  },
  {
    rank: 107,
    name: "Portland",
    slug: "portland",
    country: "United States",
    region: "OR",
    lat: 45.5152,
    lng: -122.6784,
    airportCodes: ["PDX"],
  },
  {
    rank: 108,
    name: "Charlotte",
    slug: "charlotte",
    country: "United States",
    region: "NC",
    lat: 35.2271,
    lng: -80.8431,
    airportCodes: ["CLT"],
  },
  {
    rank: 109,
    name: "Tampa",
    slug: "tampa",
    country: "United States",
    region: "FL",
    lat: 27.9506,
    lng: -82.4572,
    airportCodes: ["TPA"],
  },
  {
    rank: 110,
    name: "Minneapolis",
    slug: "minneapolis",
    country: "United States",
    region: "MN",
    lat: 44.9778,
    lng: -93.265,
    airportCodes: ["MSP"],
  },
  {
    rank: 111,
    name: "Detroit",
    slug: "detroit",
    country: "United States",
    region: "MI",
    lat: 42.3314,
    lng: -83.0458,
    airportCodes: ["DTW"],
  },
  {
    rank: 112,
    name: "Salt Lake City",
    slug: "salt-lake-city",
    country: "United States",
    region: "UT",
    lat: 40.7608,
    lng: -111.891,
    airportCodes: ["SLC"],
  },
  {
    rank: 113,
    name: "Raleigh",
    slug: "raleigh",
    country: "United States",
    region: "NC",
    lat: 35.7796,
    lng: -78.6382,
    airportCodes: ["RDU"],
  },
  {
    rank: 114,
    name: "San Antonio",
    slug: "san-antonio",
    country: "United States",
    region: "TX",
    lat: 29.4241,
    lng: -98.4936,
    airportCodes: ["SAT"],
  },
  {
    rank: 115,
    name: "Savannah",
    slug: "savannah",
    country: "United States",
    region: "GA",
    lat: 32.0809,
    lng: -81.0912,
    airportCodes: ["SAV"],
  },
  {
    rank: 116,
    name: "Charleston",
    slug: "charleston",
    country: "United States",
    region: "SC",
    lat: 32.7765,
    lng: -79.9311,
    airportCodes: ["CHS"],
  },
  {
    rank: 117,
    name: "Valencia",
    slug: "valencia",
    country: "Spain",
    region: "Valencian Community",
    lat: 39.4699,
    lng: -0.3763,
    airportCodes: ["VLC"],
  },
  {
    rank: 118,
    name: "Seville",
    slug: "seville",
    country: "Spain",
    region: "Andalusia",
    lat: 37.3891,
    lng: -5.9845,
    airportCodes: ["SVQ"],
  },
  {
    rank: 119,
    name: "Malaga",
    slug: "malaga",
    country: "Spain",
    region: "Andalusia",
    lat: 36.7213,
    lng: -4.4214,
    airportCodes: ["AGP"],
  },
  {
    rank: 120,
    name: "Naples",
    slug: "naples",
    country: "Italy",
    region: "Campania",
    lat: 40.8518,
    lng: 14.2681,
    airportCodes: ["NAP"],
  },
  {
    rank: 121,
    name: "Palermo",
    slug: "palermo",
    country: "Italy",
    region: "Sicily",
    lat: 38.1157,
    lng: 13.3615,
    airportCodes: ["PMO"],
  },
  {
    rank: 122,
    name: "Warsaw",
    slug: "warsaw",
    country: "Poland",
    region: "Mazovia",
    lat: 52.2297,
    lng: 21.0122,
    airportCodes: ["WAW"],
  },
  {
    rank: 123,
    name: "Krakow",
    slug: "krakow",
    country: "Poland",
    region: "Lesser Poland",
    lat: 50.0647,
    lng: 19.945,
    airportCodes: ["KRK"],
  },
  {
    rank: 124,
    name: "Bucharest",
    slug: "bucharest",
    country: "Romania",
    region: "Bucharest",
    lat: 44.4268,
    lng: 26.1025,
    airportCodes: ["OTP"],
  },
  {
    rank: 125,
    name: "Sofia",
    slug: "sofia",
    country: "Bulgaria",
    region: "Sofia City Province",
    lat: 42.6977,
    lng: 23.3219,
    airportCodes: ["SOF"],
  },
  {
    rank: 126,
    name: "Tallinn",
    slug: "tallinn",
    country: "Estonia",
    region: "Harju",
    lat: 59.437,
    lng: 24.7536,
    airportCodes: ["TLL"],
  },
  {
    rank: 127,
    name: "Riga",
    slug: "riga",
    country: "Latvia",
    region: "Riga",
    lat: 56.9496,
    lng: 24.1052,
    airportCodes: ["RIX"],
  },
  {
    rank: 128,
    name: "Vilnius",
    slug: "vilnius",
    country: "Lithuania",
    region: "Vilnius County",
    lat: 54.6872,
    lng: 25.2797,
    airportCodes: ["VNO"],
  },
  {
    rank: 129,
    name: "Dubrovnik",
    slug: "dubrovnik",
    country: "Croatia",
    region: "Dubrovnik-Neretva",
    lat: 42.6507,
    lng: 18.0944,
    airportCodes: ["DBV"],
  },
  {
    rank: 130,
    name: "Split",
    slug: "split",
    country: "Croatia",
    region: "Split-Dalmatia",
    lat: 43.5081,
    lng: 16.4402,
    airportCodes: ["SPU"],
  },
  {
    rank: 131,
    name: "Ljubljana",
    slug: "ljubljana",
    country: "Slovenia",
    region: "Central Slovenia",
    lat: 46.0569,
    lng: 14.5058,
    airportCodes: ["LJU"],
  },
  {
    rank: 132,
    name: "Amman",
    slug: "amman",
    country: "Jordan",
    region: "Amman",
    lat: 31.9539,
    lng: 35.9106,
    airportCodes: ["AMM"],
  },
  {
    rank: 133,
    name: "Muscat",
    slug: "muscat",
    country: "Oman",
    region: "Muscat",
    lat: 23.588,
    lng: 58.3829,
    airportCodes: ["MCT"],
  },
  {
    rank: 134,
    name: "Addis Ababa",
    slug: "addis-ababa",
    country: "Ethiopia",
    region: "Addis Ababa",
    lat: 8.9806,
    lng: 38.7578,
    airportCodes: ["ADD"],
  },
  {
    rank: 135,
    name: "Accra",
    slug: "accra",
    country: "Ghana",
    region: "Greater Accra",
    lat: 5.6037,
    lng: -0.187,
    airportCodes: ["ACC"],
  },
  {
    rank: 136,
    name: "Port Louis",
    slug: "port-louis",
    country: "Mauritius",
    region: "Port Louis",
    lat: -20.1609,
    lng: 57.5012,
    airportCodes: ["MRU"],
  },
  {
    rank: 137,
    name: "Zanzibar City",
    slug: "zanzibar-city",
    country: "Tanzania",
    region: "Zanzibar Urban",
    lat: -6.1659,
    lng: 39.2026,
    airportCodes: ["ZNZ"],
  },
  {
    rank: 138,
    name: "Colombo",
    slug: "colombo",
    country: "Sri Lanka",
    region: "Western Province",
    lat: 6.9271,
    lng: 79.8612,
    airportCodes: ["CMB"],
  },
  {
    rank: 139,
    name: "Male",
    slug: "male",
    country: "Maldives",
    region: "Kaafu",
    lat: 4.1755,
    lng: 73.5093,
    airportCodes: ["MLE"],
  },
  {
    rank: 140,
    name: "Kathmandu",
    slug: "kathmandu",
    country: "Nepal",
    region: "Bagmati",
    lat: 27.7172,
    lng: 85.324,
    airportCodes: ["KTM"],
  },
  {
    rank: 141,
    name: "Manila",
    slug: "manila",
    country: "Philippines",
    region: "Metro Manila",
    lat: 14.5995,
    lng: 120.9842,
    airportCodes: ["MNL"],
  },
  {
    rank: 142,
    name: "Cebu",
    slug: "cebu",
    country: "Philippines",
    region: "Central Visayas",
    lat: 10.3157,
    lng: 123.8854,
    airportCodes: ["CEB"],
  },
  {
    rank: 143,
    name: "Da Nang",
    slug: "da-nang",
    country: "Vietnam",
    region: "Da Nang",
    lat: 16.0544,
    lng: 108.2022,
    airportCodes: ["DAD"],
  },
  {
    rank: 144,
    name: "Siem Reap",
    slug: "siem-reap",
    country: "Cambodia",
    region: "Siem Reap",
    lat: 13.3671,
    lng: 103.8448,
    airportCodes: ["SAI"],
  },
  {
    rank: 145,
    name: "Penang",
    slug: "penang",
    country: "Malaysia",
    region: "Penang",
    lat: 5.4164,
    lng: 100.3327,
    airportCodes: ["PEN"],
  },
  {
    rank: 146,
    name: "Sapporo",
    slug: "sapporo",
    country: "Japan",
    region: "Hokkaido",
    lat: 43.0618,
    lng: 141.3545,
    airportCodes: ["CTS"],
  },
  {
    rank: 147,
    name: "Fukuoka",
    slug: "fukuoka",
    country: "Japan",
    region: "Fukuoka",
    lat: 33.5902,
    lng: 130.4017,
    airportCodes: ["FUK"],
  },
  {
    rank: 148,
    name: "Hiroshima",
    slug: "hiroshima",
    country: "Japan",
    region: "Hiroshima",
    lat: 34.3853,
    lng: 132.4553,
    airportCodes: ["HIJ"],
  },
  {
    rank: 149,
    name: "Chengdu",
    slug: "chengdu",
    country: "China",
    region: "Sichuan",
    lat: 30.5728,
    lng: 104.0668,
    airportCodes: ["CTU"],
  },
  {
    rank: 150,
    name: "Adelaide",
    slug: "adelaide",
    country: "Australia",
    region: "SA",
    lat: -34.9285,
    lng: 138.6007,
    airportCodes: ["ADL"],
  },
];
