import { SEED_CONFIG } from "../config/seed-config.js";

export const TOP_TRAVEL_CITIES = [
  {
    rank: 1,
    name: "New York",
    slug: "new-york",
    country: "United States",
    region: "NY",
    lat: 40.7128,
    lng: -74.006,
    airportCodes: ["JFK", "LGA", "EWR"],
    aliases: ["new york city", "nyc"],
  },
  {
    rank: 2,
    name: "Los Angeles",
    slug: "los-angeles",
    country: "United States",
    region: "CA",
    lat: 34.0522,
    lng: -118.2437,
    airportCodes: ["LAX", "BUR", "LGB"],
  },
  {
    rank: 3,
    name: "Las Vegas",
    slug: "las-vegas",
    country: "United States",
    region: "NV",
    lat: 36.1699,
    lng: -115.1398,
    airportCodes: ["LAS"],
  },
  {
    rank: 4,
    name: "Orlando",
    slug: "orlando",
    country: "United States",
    region: "FL",
    lat: 28.5383,
    lng: -81.3792,
    airportCodes: ["MCO"],
  },
  {
    rank: 5,
    name: "Miami",
    slug: "miami",
    country: "United States",
    region: "FL",
    lat: 25.7617,
    lng: -80.1918,
    airportCodes: ["MIA", "FLL"],
  },
  {
    rank: 6,
    name: "Chicago",
    slug: "chicago",
    country: "United States",
    region: "IL",
    lat: 41.8781,
    lng: -87.6298,
    airportCodes: ["ORD", "MDW"],
  },
  {
    rank: 7,
    name: "San Francisco",
    slug: "san-francisco",
    country: "United States",
    region: "CA",
    lat: 37.7749,
    lng: -122.4194,
    airportCodes: ["SFO", "OAK", "SJC"],
  },
  {
    rank: 8,
    name: "Washington",
    slug: "washington-dc",
    country: "United States",
    region: "DC",
    lat: 38.9072,
    lng: -77.0369,
    airportCodes: ["IAD", "DCA", "BWI"],
    aliases: ["washington dc", "dc"],
  },
  {
    rank: 9,
    name: "Boston",
    slug: "boston",
    country: "United States",
    region: "MA",
    lat: 42.3601,
    lng: -71.0589,
    airportCodes: ["BOS"],
  },
  {
    rank: 10,
    name: "Seattle",
    slug: "seattle",
    country: "United States",
    region: "WA",
    lat: 47.6062,
    lng: -122.3321,
    airportCodes: ["SEA", "BFI"],
  },
  {
    rank: 11,
    name: "San Diego",
    slug: "san-diego",
    country: "United States",
    region: "CA",
    lat: 32.7157,
    lng: -117.1611,
    airportCodes: ["SAN"],
  },
  {
    rank: 12,
    name: "Honolulu",
    slug: "honolulu",
    country: "United States",
    region: "HI",
    lat: 21.3069,
    lng: -157.8583,
    airportCodes: ["HNL"],
  },
  {
    rank: 13,
    name: "Nashville",
    slug: "nashville",
    country: "United States",
    region: "TN",
    lat: 36.1627,
    lng: -86.7816,
    airportCodes: ["BNA"],
  },
  {
    rank: 14,
    name: "New Orleans",
    slug: "new-orleans",
    country: "United States",
    region: "LA",
    lat: 29.9511,
    lng: -90.0715,
    airportCodes: ["MSY"],
  },
  {
    rank: 15,
    name: "Toronto",
    slug: "toronto",
    country: "Canada",
    region: "ON",
    lat: 43.6532,
    lng: -79.3832,
    airportCodes: ["YYZ", "YTZ"],
  },
  {
    rank: 16,
    name: "Vancouver",
    slug: "vancouver",
    country: "Canada",
    region: "BC",
    lat: 49.2827,
    lng: -123.1207,
    airportCodes: ["YVR"],
  },
  {
    rank: 17,
    name: "Montreal",
    slug: "montreal",
    country: "Canada",
    region: "QC",
    lat: 45.5017,
    lng: -73.5673,
    airportCodes: ["YUL"],
  },
  {
    rank: 18,
    name: "Mexico City",
    slug: "mexico-city",
    country: "Mexico",
    region: "CDMX",
    lat: 19.4326,
    lng: -99.1332,
    airportCodes: ["MEX"],
  },
  {
    rank: 19,
    name: "Cancun",
    slug: "cancun",
    country: "Mexico",
    region: "Quintana Roo",
    lat: 21.1619,
    lng: -86.8515,
    airportCodes: ["CUN"],
  },
  {
    rank: 20,
    name: "Cabo San Lucas",
    slug: "cabo-san-lucas",
    country: "Mexico",
    region: "Baja California Sur",
    lat: 22.8905,
    lng: -109.9167,
    airportCodes: ["SJD"],
  },
  {
    rank: 21,
    name: "Puerto Vallarta",
    slug: "puerto-vallarta",
    country: "Mexico",
    region: "Jalisco",
    lat: 20.6534,
    lng: -105.2253,
    airportCodes: ["PVR"],
  },
  {
    rank: 22,
    name: "San Juan",
    slug: "san-juan",
    country: "Puerto Rico",
    region: "PR",
    lat: 18.4655,
    lng: -66.1057,
    airportCodes: ["SJU"],
  },
  {
    rank: 23,
    name: "Rio de Janeiro",
    slug: "rio-de-janeiro",
    country: "Brazil",
    region: "RJ",
    lat: -22.9068,
    lng: -43.1729,
    airportCodes: ["GIG", "SDU"],
  },
  {
    rank: 24,
    name: "Sao Paulo",
    slug: "sao-paulo",
    country: "Brazil",
    region: "SP",
    lat: -23.5558,
    lng: -46.6396,
    airportCodes: ["GRU", "CGH"],
  },
  {
    rank: 25,
    name: "Buenos Aires",
    slug: "buenos-aires",
    country: "Argentina",
    region: "CABA",
    lat: -34.6037,
    lng: -58.3816,
    airportCodes: ["EZE", "AEP"],
  },
  {
    rank: 26,
    name: "Lima",
    slug: "lima",
    country: "Peru",
    region: "Lima",
    lat: -12.0464,
    lng: -77.0428,
    airportCodes: ["LIM"],
  },
  {
    rank: 27,
    name: "Santiago",
    slug: "santiago",
    country: "Chile",
    region: "Santiago Metropolitan",
    lat: -33.4489,
    lng: -70.6693,
    airportCodes: ["SCL"],
  },
  {
    rank: 28,
    name: "Bogota",
    slug: "bogota",
    country: "Colombia",
    region: "Bogota",
    lat: 4.711,
    lng: -74.0721,
    airportCodes: ["BOG"],
  },
  {
    rank: 29,
    name: "London",
    slug: "london",
    country: "United Kingdom",
    region: "England",
    lat: 51.5072,
    lng: -0.1276,
    airportCodes: ["LHR", "LGW", "STN"],
  },
  {
    rank: 30,
    name: "Paris",
    slug: "paris",
    country: "France",
    region: "Ile-de-France",
    lat: 48.8566,
    lng: 2.3522,
    airportCodes: ["CDG", "ORY"],
  },
  {
    rank: 31,
    name: "Rome",
    slug: "rome",
    country: "Italy",
    region: "Lazio",
    lat: 41.9028,
    lng: 12.4964,
    airportCodes: ["FCO", "CIA"],
  },
  {
    rank: 32,
    name: "Milan",
    slug: "milan",
    country: "Italy",
    region: "Lombardy",
    lat: 45.4642,
    lng: 9.19,
    airportCodes: ["MXP", "LIN", "BGY"],
  },
  {
    rank: 33,
    name: "Venice",
    slug: "venice",
    country: "Italy",
    region: "Veneto",
    lat: 45.4408,
    lng: 12.3155,
    airportCodes: ["VCE", "TSF"],
  },
  {
    rank: 34,
    name: "Florence",
    slug: "florence",
    country: "Italy",
    region: "Tuscany",
    lat: 43.7696,
    lng: 11.2558,
    airportCodes: ["FLR", "PSA"],
  },
  {
    rank: 35,
    name: "Barcelona",
    slug: "barcelona",
    country: "Spain",
    region: "Catalonia",
    lat: 41.3851,
    lng: 2.1734,
    airportCodes: ["BCN"],
  },
  {
    rank: 36,
    name: "Madrid",
    slug: "madrid",
    country: "Spain",
    region: "Community of Madrid",
    lat: 40.4168,
    lng: -3.7038,
    airportCodes: ["MAD"],
  },
  {
    rank: 37,
    name: "Lisbon",
    slug: "lisbon",
    country: "Portugal",
    region: "Lisbon District",
    lat: 38.7223,
    lng: -9.1393,
    airportCodes: ["LIS"],
  },
  {
    rank: 38,
    name: "Porto",
    slug: "porto",
    country: "Portugal",
    region: "Porto District",
    lat: 41.1579,
    lng: -8.6291,
    airportCodes: ["OPO"],
  },
  {
    rank: 39,
    name: "Amsterdam",
    slug: "amsterdam",
    country: "Netherlands",
    region: "North Holland",
    lat: 52.3676,
    lng: 4.9041,
    airportCodes: ["AMS"],
  },
  {
    rank: 40,
    name: "Berlin",
    slug: "berlin",
    country: "Germany",
    region: "Berlin",
    lat: 52.52,
    lng: 13.405,
    airportCodes: ["BER"],
  },
  {
    rank: 41,
    name: "Munich",
    slug: "munich",
    country: "Germany",
    region: "Bavaria",
    lat: 48.1351,
    lng: 11.582,
    airportCodes: ["MUC"],
  },
  {
    rank: 42,
    name: "Frankfurt",
    slug: "frankfurt",
    country: "Germany",
    region: "Hesse",
    lat: 50.1109,
    lng: 8.6821,
    airportCodes: ["FRA"],
  },
  {
    rank: 43,
    name: "Prague",
    slug: "prague",
    country: "Czechia",
    region: "Prague",
    lat: 50.0755,
    lng: 14.4378,
    airportCodes: ["PRG"],
  },
  {
    rank: 44,
    name: "Vienna",
    slug: "vienna",
    country: "Austria",
    region: "Vienna",
    lat: 48.2082,
    lng: 16.3738,
    airportCodes: ["VIE"],
  },
  {
    rank: 45,
    name: "Budapest",
    slug: "budapest",
    country: "Hungary",
    region: "Central Hungary",
    lat: 47.4979,
    lng: 19.0402,
    airportCodes: ["BUD"],
  },
  {
    rank: 46,
    name: "Athens",
    slug: "athens",
    country: "Greece",
    region: "Attica",
    lat: 37.9838,
    lng: 23.7275,
    airportCodes: ["ATH"],
  },
  {
    rank: 47,
    name: "Istanbul",
    slug: "istanbul",
    country: "Turkey",
    region: "Marmara",
    lat: 41.0082,
    lng: 28.9784,
    airportCodes: ["IST", "SAW"],
  },
  {
    rank: 48,
    name: "Dublin",
    slug: "dublin",
    country: "Ireland",
    region: "Leinster",
    lat: 53.3498,
    lng: -6.2603,
    airportCodes: ["DUB"],
  },
  {
    rank: 49,
    name: "Edinburgh",
    slug: "edinburgh",
    country: "United Kingdom",
    region: "Scotland",
    lat: 55.9533,
    lng: -3.1883,
    airportCodes: ["EDI"],
  },
  {
    rank: 50,
    name: "Zurich",
    slug: "zurich",
    country: "Switzerland",
    region: "Zurich",
    lat: 47.3769,
    lng: 8.5417,
    airportCodes: ["ZRH"],
  },
  {
    rank: 51,
    name: "Geneva",
    slug: "geneva",
    country: "Switzerland",
    region: "Geneva",
    lat: 46.2044,
    lng: 6.1432,
    airportCodes: ["GVA"],
  },
  {
    rank: 52,
    name: "Brussels",
    slug: "brussels",
    country: "Belgium",
    region: "Brussels-Capital",
    lat: 50.8503,
    lng: 4.3517,
    airportCodes: ["BRU"],
  },
  {
    rank: 53,
    name: "Copenhagen",
    slug: "copenhagen",
    country: "Denmark",
    region: "Capital Region",
    lat: 55.6761,
    lng: 12.5683,
    airportCodes: ["CPH"],
  },
  {
    rank: 54,
    name: "Stockholm",
    slug: "stockholm",
    country: "Sweden",
    region: "Stockholm County",
    lat: 59.3293,
    lng: 18.0686,
    airportCodes: ["ARN"],
  },
  {
    rank: 55,
    name: "Oslo",
    slug: "oslo",
    country: "Norway",
    region: "Oslo",
    lat: 59.9139,
    lng: 10.7522,
    airportCodes: ["OSL"],
  },
  {
    rank: 56,
    name: "Helsinki",
    slug: "helsinki",
    country: "Finland",
    region: "Uusimaa",
    lat: 60.1699,
    lng: 24.9384,
    airportCodes: ["HEL"],
  },
  {
    rank: 57,
    name: "Reykjavik",
    slug: "reykjavik",
    country: "Iceland",
    region: "Capital Region",
    lat: 64.1466,
    lng: -21.9426,
    airportCodes: ["KEF"],
  },
  {
    rank: 58,
    name: "Nice",
    slug: "nice",
    country: "France",
    region: "Provence-Alpes-Cote d'Azur",
    lat: 43.7102,
    lng: 7.262,
    airportCodes: ["NCE"],
  },
  {
    rank: 59,
    name: "Dubai",
    slug: "dubai",
    country: "United Arab Emirates",
    region: "Dubai",
    lat: 25.2048,
    lng: 55.2708,
    airportCodes: ["DXB", "DWC"],
  },
  {
    rank: 60,
    name: "Abu Dhabi",
    slug: "abu-dhabi",
    country: "United Arab Emirates",
    region: "Abu Dhabi",
    lat: 24.4539,
    lng: 54.3773,
    airportCodes: ["AUH"],
  },
  {
    rank: 61,
    name: "Doha",
    slug: "doha",
    country: "Qatar",
    region: "Doha Municipality",
    lat: 25.2854,
    lng: 51.531,
    airportCodes: ["DOH"],
  },
  {
    rank: 62,
    name: "Riyadh",
    slug: "riyadh",
    country: "Saudi Arabia",
    region: "Riyadh",
    lat: 24.7136,
    lng: 46.6753,
    airportCodes: ["RUH"],
  },
  {
    rank: 63,
    name: "Jeddah",
    slug: "jeddah",
    country: "Saudi Arabia",
    region: "Makkah",
    lat: 21.4858,
    lng: 39.1925,
    airportCodes: ["JED"],
  },
  {
    rank: 64,
    name: "Tel Aviv",
    slug: "tel-aviv",
    country: "Israel",
    region: "Tel Aviv District",
    lat: 32.0853,
    lng: 34.7818,
    airportCodes: ["TLV"],
  },
  {
    rank: 65,
    name: "Cairo",
    slug: "cairo",
    country: "Egypt",
    region: "Cairo Governorate",
    lat: 30.0444,
    lng: 31.2357,
    airportCodes: ["CAI"],
  },
  {
    rank: 66,
    name: "Marrakech",
    slug: "marrakech",
    country: "Morocco",
    region: "Marrakesh-Safi",
    lat: 31.6295,
    lng: -7.9811,
    airportCodes: ["RAK"],
  },
  {
    rank: 67,
    name: "Cape Town",
    slug: "cape-town",
    country: "South Africa",
    region: "Western Cape",
    lat: -33.9249,
    lng: 18.4241,
    airportCodes: ["CPT"],
  },
  {
    rank: 68,
    name: "Johannesburg",
    slug: "johannesburg",
    country: "South Africa",
    region: "Gauteng",
    lat: -26.2041,
    lng: 28.0473,
    airportCodes: ["JNB"],
  },
  {
    rank: 69,
    name: "Nairobi",
    slug: "nairobi",
    country: "Kenya",
    region: "Nairobi County",
    lat: -1.2921,
    lng: 36.8219,
    airportCodes: ["NBO"],
  },
  {
    rank: 70,
    name: "Tokyo",
    slug: "tokyo",
    country: "Japan",
    region: "Tokyo",
    lat: 35.6762,
    lng: 139.6503,
    airportCodes: ["HND", "NRT"],
  },
  {
    rank: 71,
    name: "Osaka",
    slug: "osaka",
    country: "Japan",
    region: "Osaka",
    lat: 34.6937,
    lng: 135.5023,
    airportCodes: ["KIX", "ITM"],
  },
  {
    rank: 72,
    name: "Kyoto",
    slug: "kyoto",
    country: "Japan",
    region: "Kyoto",
    lat: 35.0116,
    lng: 135.7681,
    airportCodes: ["ITM", "KIX"],
  },
  {
    rank: 73,
    name: "Seoul",
    slug: "seoul",
    country: "South Korea",
    region: "Seoul",
    lat: 37.5665,
    lng: 126.978,
    airportCodes: ["ICN", "GMP"],
  },
  {
    rank: 74,
    name: "Busan",
    slug: "busan",
    country: "South Korea",
    region: "Busan",
    lat: 35.1796,
    lng: 129.0756,
    airportCodes: ["PUS"],
  },
  {
    rank: 75,
    name: "Singapore",
    slug: "singapore",
    country: "Singapore",
    region: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    airportCodes: ["SIN"],
  },
  {
    rank: 76,
    name: "Bangkok",
    slug: "bangkok",
    country: "Thailand",
    region: "Bangkok",
    lat: 13.7563,
    lng: 100.5018,
    airportCodes: ["BKK", "DMK"],
  },
  {
    rank: 77,
    name: "Phuket",
    slug: "phuket",
    country: "Thailand",
    region: "Phuket",
    lat: 7.8804,
    lng: 98.3923,
    airportCodes: ["HKT"],
  },
  {
    rank: 78,
    name: "Chiang Mai",
    slug: "chiang-mai",
    country: "Thailand",
    region: "Chiang Mai",
    lat: 18.7883,
    lng: 98.9853,
    airportCodes: ["CNX"],
  },
  {
    rank: 79,
    name: "Hanoi",
    slug: "hanoi",
    country: "Vietnam",
    region: "Hanoi",
    lat: 21.0278,
    lng: 105.8342,
    airportCodes: ["HAN"],
  },
  {
    rank: 80,
    name: "Ho Chi Minh City",
    slug: "ho-chi-minh-city",
    country: "Vietnam",
    region: "Ho Chi Minh",
    lat: 10.8231,
    lng: 106.6297,
    airportCodes: ["SGN"],
    aliases: ["saigon"],
  },
  {
    rank: 81,
    name: "Denpasar",
    slug: "denpasar",
    country: "Indonesia",
    region: "Bali",
    lat: -8.65,
    lng: 115.2167,
    airportCodes: ["DPS"],
    aliases: ["bali"],
  },
  {
    rank: 82,
    name: "Jakarta",
    slug: "jakarta",
    country: "Indonesia",
    region: "Jakarta",
    lat: -6.2088,
    lng: 106.8456,
    airportCodes: ["CGK"],
  },
  {
    rank: 83,
    name: "Kuala Lumpur",
    slug: "kuala-lumpur",
    country: "Malaysia",
    region: "Federal Territory",
    lat: 3.139,
    lng: 101.6869,
    airportCodes: ["KUL"],
  },
  {
    rank: 84,
    name: "Hong Kong",
    slug: "hong-kong",
    country: "Hong Kong",
    region: "Hong Kong",
    lat: 22.3193,
    lng: 114.1694,
    airportCodes: ["HKG"],
  },
  {
    rank: 85,
    name: "Taipei",
    slug: "taipei",
    country: "Taiwan",
    region: "Taipei",
    lat: 25.033,
    lng: 121.5654,
    airportCodes: ["TPE"],
  },
  {
    rank: 86,
    name: "Shanghai",
    slug: "shanghai",
    country: "China",
    region: "Shanghai",
    lat: 31.2304,
    lng: 121.4737,
    airportCodes: ["PVG", "SHA"],
  },
  {
    rank: 87,
    name: "Beijing",
    slug: "beijing",
    country: "China",
    region: "Beijing",
    lat: 39.9042,
    lng: 116.4074,
    airportCodes: ["PEK", "PKX"],
  },
  {
    rank: 88,
    name: "Guangzhou",
    slug: "guangzhou",
    country: "China",
    region: "Guangdong",
    lat: 23.1291,
    lng: 113.2644,
    airportCodes: ["CAN"],
  },
  {
    rank: 89,
    name: "Shenzhen",
    slug: "shenzhen",
    country: "China",
    region: "Guangdong",
    lat: 22.5431,
    lng: 114.0579,
    airportCodes: ["SZX"],
  },
  {
    rank: 90,
    name: "Delhi",
    slug: "delhi",
    country: "India",
    region: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    airportCodes: ["DEL"],
  },
  {
    rank: 91,
    name: "Mumbai",
    slug: "mumbai",
    country: "India",
    region: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    airportCodes: ["BOM"],
  },
  {
    rank: 92,
    name: "Bengaluru",
    slug: "bengaluru",
    country: "India",
    region: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    airportCodes: ["BLR"],
    aliases: ["bangalore"],
  },
  {
    rank: 93,
    name: "Chennai",
    slug: "chennai",
    country: "India",
    region: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    airportCodes: ["MAA"],
  },
  {
    rank: 94,
    name: "Sydney",
    slug: "sydney",
    country: "Australia",
    region: "NSW",
    lat: -33.8688,
    lng: 151.2093,
    airportCodes: ["SYD"],
  },
  {
    rank: 95,
    name: "Melbourne",
    slug: "melbourne",
    country: "Australia",
    region: "VIC",
    lat: -37.8136,
    lng: 144.9631,
    airportCodes: ["MEL"],
  },
  {
    rank: 96,
    name: "Brisbane",
    slug: "brisbane",
    country: "Australia",
    region: "QLD",
    lat: -27.4698,
    lng: 153.0251,
    airportCodes: ["BNE"],
  },
  {
    rank: 97,
    name: "Perth",
    slug: "perth",
    country: "Australia",
    region: "WA",
    lat: -31.9523,
    lng: 115.8613,
    airportCodes: ["PER"],
  },
  {
    rank: 98,
    name: "Auckland",
    slug: "auckland",
    country: "New Zealand",
    region: "Auckland",
    lat: -36.8509,
    lng: 174.7645,
    airportCodes: ["AKL"],
  },
  {
    rank: 99,
    name: "Queenstown",
    slug: "queenstown",
    country: "New Zealand",
    region: "Otago",
    lat: -45.0312,
    lng: 168.6626,
    airportCodes: ["ZQN"],
  },
  {
    rank: 100,
    name: "Denver",
    slug: "denver",
    country: "United States",
    region: "CO",
    lat: 39.7392,
    lng: -104.9903,
    airportCodes: ["DEN"],
  },
];

export const TOP_TRAVEL_CITIES_BY_SLUG = Object.fromEntries(
  TOP_TRAVEL_CITIES.map((city) => [city.slug, city]),
);

const normalizeToken = (value) => {
  return String(value || "")
    .normalize("NFKD")
    .replaceAll(/[\u0300-\u036f]/g, "")
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/(^-|-$)/g, "");
};

export const findTopTravelCity = (value) => {
  const token = normalizeToken(value);
  if (!token) return null;

  const bySlug = TOP_TRAVEL_CITIES_BY_SLUG[token];
  if (bySlug) return bySlug;

  return (
    TOP_TRAVEL_CITIES.find((city) => {
      if (normalizeToken(city.name) === token) return true;
      if (
        Array.isArray(city.aliases) &&
        city.aliases.some((alias) => normalizeToken(alias) === token)
      )
        return true;
      return false;
    }) || null
  );
};

export const getTopTravelCities = () => {
  return TOP_TRAVEL_CITIES.slice(0, SEED_CONFIG.topCityCount);
};
