export const FLIGHT_PROVIDER_NAME = 'flight-default'
export const FLIGHT_PROVIDER_REGISTRY_ALIAS = 'flight'

export const DEFAULT_FLIGHT_PROVIDER_SEARCH_LIMIT = 30
export const DEFAULT_FLIGHT_PROVIDER_TIMEOUT_MS = 5_000
export const DEFAULT_FLIGHT_PROVIDER_RETRIES = 0
