export const HOTEL_PROVIDER_NAME = 'hotel-default'
export const HOTEL_PROVIDER_REGISTRY_ALIAS = 'hotel'

export const DEFAULT_HOTEL_PROVIDER_SEARCH_LIMIT = 24
export const DEFAULT_HOTEL_PROVIDER_TIMEOUT_MS = 5_000
export const DEFAULT_HOTEL_PROVIDER_RETRIES = 0
export const DEFAULT_HOTEL_PROVIDER_MAX_OFFERS_PER_HOTEL = 4
